// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAlIqxqscXQSW1CqIbSmC7aSylZbVy1NiQ',
    appId: '1:277899685082:web:80108f432458ff11c3c9e3',
    messagingSenderId: '277899685082',
    projectId: 'nutrimeal-fyp',
    authDomain: 'nutrimeal-fyp.firebaseapp.com',
    storageBucket: 'nutrimeal-fyp.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBiHhWj_HoHQ_SFg3RXym8__QgpOAPfqNg',
    appId: '1:277899685082:android:80fa69f7f3e7a622c3c9e3',
    messagingSenderId: '277899685082',
    projectId: 'nutrimeal-fyp',
    storageBucket: 'nutrimeal-fyp.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBdzflUR6x-9LvwJh73vC8-wsK9Gup2d3A',
    appId: '1:277899685082:ios:057ad0c69d050393c3c9e3',
    messagingSenderId: '277899685082',
    projectId: 'nutrimeal-fyp',
    storageBucket: 'nutrimeal-fyp.appspot.com',
    iosBundleId: 'com.example.nutrimeal',
  );
}
